### ISSUE TITLE
[Suggestion] Add minecraft.net's articles to the page

### ISSUE THREAD

**Issue by vico93** [olauncher/olauncher.github.io#2]
Well, why not turn this page into a "mirror" of the [Minecraft's article list](https://www.minecraft.net/en-us/articles) with the classic layout.

Basically, it would "import" the title and the text content of the article, and the title link would point to the article straight in Minecraft's website.

Unfortunately MC website doesn't have a RSS feed that could help in automatize this, but [someone tried to do something about it](https://github.com/Triteras/MinecraftNewsRSS), so i think its possible to do, but it would require some work.

**Comment by DevBefell** [comment]
That is something I was looking at, and there is something "unofficial", using Minecraft's internal links there is [this](https://www.minecraft.net/content/minecraft-net/_jcr_content.articles.grid?tileselection=auto&tagsPath=minecraft:article/news&propResPath=/content/minecraft-net/language-masters/en-us/articles/jcr:content/root/generic-container/par/bleeding_page_sectio/page-section-par/grid_copy&offset=8&count=2000&pageSize=8&locale=en-us&lang=/content/minecraft-net/language-masters/en-us). and with that you can control how many you receive, what type of content etc.  but going back to the point, I can't say much for figboot but I personally think that the news should be just straightforward news of versions and just about it, it would be too "clogged".

**Comment by exrodev** [comment]
This is a valid suggestion but in my mind, the idea of the news page is to stay true to the format they used many years ago, where they only really made posts for major versions. Minecraft makes articles about everything now which I don't think would suit the format that we use. I can also see it being difficult to add some automated system to continue the "Removed Herobrine" tradition in the patch notes. We shall wait to see what @bigfoot547 thinks.

**Comment by bigfoot547** [comment]
I don't enjoy working on the web side of olauncher very much, so I don't foresee many large changes to this. You can specify a custom URL for the news area using JVM properties though like so:

`java -Ddev.figboot.olauncher.URLNews="https://some-url.com" -jar olauncher.jar`
